name: .NET CI DevSecOps

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  checkout-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore


  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: checkout-build

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Execute Unit Tests
        run: dotnet test --configuration Release


  sonar-analysis:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=GitHub-Actions-CI
            -Dsonar.organization=jeevaas
            -Dsonar.sources=.


  quality-gate:
    name: Sonar Quality Gate
    runs-on: ubuntu-latest
    needs: sonar-analysis
    continue-on-error: true

    steps:
      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    needs: quality-gate
    if: always()

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Packages
        run: dotnet restore

      - name: Publish Application
        run: dotnet publish -c Release -o publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish/
