name: .NET CI DevSecOps

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/Enterprise.Web/Enterprise.Web.csproj

      - name: Build
        run: dotnet build src/Enterprise.Web/Enterprise.Web.csproj --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run Tests
        run: dotnet test src/Enterprise.Web/Enterprise.Web.csproj --configuration Release

  sonar:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=GitHub-Actions-CI
            -Dsonar.organization=jeevaas
            -Dsonar.sources=src/Enterprise.Web

  sbom:
    runs-on: ubuntu-latest
    needs: sonar

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install CycloneDX
        run: dotnet tool install --global CycloneDX

      - name: Generate SBOM
        run: |
          ~/.dotnet/tools/dotnet-CycloneDX \
          src/Enterprise.Web/Enterprise.Web.csproj \
          -o sbom

      - uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: sbom

  docker:
    runs-on: ubuntu-latest
    needs: sbom

    steps:
      - uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build \
          -t enterprise-web:${{ github.run_number }} \
          -f src/Enterprise.Web/Dockerfile \
          src/Enterprise.Web

      - name: Verify Image
        run: docker images

  publish:
    runs-on: ubuntu-latest
    needs: docker
    if: always()

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: |
          dotnet publish \
          src/Enterprise.Web/Enterprise.Web.csproj \
          -c Release \
          -o publish

      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish
